# General
name                  : 'rames'
surname               : 'aliyev'
fullname              : 'ramesaliyev'
fullname_human        : 'Rameş Aliyev'
domain                : 'http://ramesaliyev.com'

# Info
description           : "Rameş Aliyev'in kişisel web sitesi."
keywords              : 'javascript, ecmascript, es6'

# System
timezone              : 'Europe/Istanbul'
include               : ['_pages']

# Filtering Content
show_drafts           : null
limit_posts           : 0

# Conversion
markdown              : kramdown
excerpt_separator     : <!--more-->

# Outputting
baseurl               : ''
permalink             : :title.html

# Sass
sass                  :
  style               : :compressed

# Scopes
defaults:
  - 
    scope             :
      path            : ''
      type            : 'pages'
    values            :
      layout          : 'page'
  -
    scope            :
      path            : ''
      type            : 'posts'
    values            :
      layout          : 'post'

  -
    scope            :
      path            : ''
      type            : 'drafts'
    values            :
      layout          : 'post'