# Basic
name:               "ramesaliyev"

# URL
baseurl:            ""
permalink:          :title.html
relative_permalinks: true
url:                 http://ramesaliyev.github.io
title:               ramesaliyev
description:         'Rameş Aliyev'
paginate:            100

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "//ramesaliyev.github.io/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
